services:
  db:
    image: mysql:8.0
    container_name: blog-database
    environment:
      MYSQL_ROOT_PASSWORD: Server123@
      MYSQL_DATABASE: blog
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - blog_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pServer123@"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: unless-stopped

  spring-app:
    image: godfrey10/dockerdeploy-fullstack:latest
    container_name: blog-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Server123@
      # Add actuator configuration
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS: always
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      # Try multiple endpoints - actuator first, then just check if port is responding
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || curl -f http://localhost:8081/ || nc -z localhost 8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s  # Give more time for app to start

volumes:
  blog_mysql_data:

networks:
  backend:
    driver: bridge